### ISSUE TITLE
Fix viewBox of distribution by SDG treemap

### ISSUE THREAD

**Issue by Rolikasi** [unicef/publicgoods-scripts#10]
While I was working on treemap improvements I found out that the [graph in registry section](https://digitalpublicgoods.net/registry/) is not fully displayed. Which results missing 4 SDGs and incorrect sizes of 6 SDGs.

**Current**
![Снимок2](https://user-images.githubusercontent.com/44370635/116301572-e1d35580-a7a8-11eb-82e2-ae678abf0e17.PNG)

**Expected**
![Снимок](https://user-images.githubusercontent.com/44370635/116301578-e26bec00-a7a8-11eb-88b9-3e559aa12c8d.PNG)

**Comment by lacabra** [comment]
Unbelievable! 🤦

I noticed at some point that some of the areas seemed to be off (like 3 and 4 are similar in the current version, but I knew for a fact that 3 was larger, and I thought that there was an error in the calculation). I'm more than surprised to realize that the calculations are probably correct, but the display is cut. 

Kudos to you 🏆
