### ISSUE TITLE
Pass initial state onto submission form

### ISSUE THREAD

**Issue by lacabra** [unicef/publicgoods-scripts#24]
If the project is deemed eligible, and the user clicks to make a submission, the answers to the nine questions that have been answered on the eligibility form should be transferred to the submission as the initial state (see [this](https://github.com/lacabra/submission-digitalpublicgoods/blob/e8b231fa23c23e45722f6252c18f59e5bc6a76f5/pages/form.js#L98), [this](https://github.com/lacabra/submission-digitalpublicgoods/blob/e8b231fa23c23e45722f6252c18f59e5bc6a76f5/pages/form.js#L105) and [this](https://github.com/lacabra/submission-digitalpublicgoods/blob/e8b231fa23c23e45722f6252c18f59e5bc6a76f5/pages/form.js#L227)) of that form and notify the user accordingly (see [this](https://github.com/lacabra/submission-digitalpublicgoods/blob/e8b231fa23c23e45722f6252c18f59e5bc6a76f5/pages/form.js#L106) and [this](https://github.com/lacabra/submission-digitalpublicgoods/blob/e8b231fa23c23e45722f6252c18f59e5bc6a76f5/pages/form.js#L199)), similar to this other notification (see blue box at the top):

![Screen Shot 2021-06-18 at 12 28 24 PM](https://user-images.githubusercontent.com/6098973/122602856-bba39680-d030-11eb-969c-1ee0508f493b.png)

FYI: @nathanbaleeta

**Comment by rachita19082** [comment]
@lacabra Thank you for the resources. I have gone through the given links, and this is what I have understood so far.

To pass the answers collected in the Eligibility Form to the Submissions form, a JSON string containing all the answers filled in the Eligibility Form needs to be passed to [form.js](https://github.com/lacabra/submission-digitalpublicgoods/blob/e8b231fa23c23e45722f6252c18f59e5bc6a76f5/pages/form.js) in the Submissions form. Here, the `initialValues` state needs to be set with the passed JSON string. 

Would you please let me know if the above approach is correct? If it is correct, I cannot figure out how the JSON can be passed from the Eligibility Form to the Submissions Form. Is there a way to pass the data into the submissions form URL where it can be directly read and rendered, or would it be required to pass it as props? Would you please direct me to some resources which could help me understand this better? Thank you.

**Comment by nathanfletcher** [comment]
Hey, @rachita19082 I have closed [#41](https://github.com/lacabra/submission-digitalpublicgoods/pull/41) so we can test and watch the results live together alongside [#34](https://github.com/unicef/publicgoods-scripts/pull/34#issuecomment-883242402)
