### ISSUE TITLE
Eligibility is not as simple as all YES

### ISSUE THREAD

**Issue by lacabra** [unicef/publicgoods-scripts#29]
The current version of the eligibility form only counts a valid answer if it is answered `Yes`, but that is not correct.

For example, indicator 4 asks "Does the license of libraries/dependencies undermine the openess of the project?" and the *correct* answer here is `No` instead of Yes

Similarly, indicator 9 asks "Does the project do no harm" and the *correct* answer is `No` instead of Yes.

Furthermore, some of the questions around eligibility cannot be reduced to a simple Yes/No answer as it may depend. Please identify which questions are Yes/No (e.g. questions 1 and 2, are Yes/No, where the correct answer is Yes, and if they answer No, they are not eligible). For the rest of the questions identify what needs to happen for them to be eligible if they provide the "wrong" answer.

Note that question 4, if they answer `No` they are eligible, but if they answer `Yes`, they are also eligible **IF** they are able to demonstrate independence from closed components (see 3rd column on indicator 4 [here](https://github.com/DPGAlliance/DPG-Standard/blob/master/standard-questions.md)).

From the discussion above, I envision that the summary should provide 3 end results: `Yes`, `No` and `Maybe` if certain conditions are met. The results page of the form should thus account for this.

@nathanbaleeta should be able to provide additional clarity around this.

Cc: @amreenp7

**Comment by rachita19082** [comment]
Based on the information provided in the [Digital Public Goods Standard](https://github.com/DPGAlliance/DPG-Standard/blob/master/standard.md), I suggest the following for the eligibility form. 

**1. Is it relevant to one of the Sustainable Development Goals?**
         `Yes`  Correct Answer
         `No`  Not eligible

**2. Does it use an appropriate open license?**
       `Yes`  Correct Answer
       `No`  Not eligible

**3. Is ownership clearly defined**
       `Yes`  Correct Answer
       `No`  Not eligible

**4. Does the license of libraries/dependencies undermine the openess of the project?**
       `Yes`  Maybe eligible IF they are able to demonstrate independence from closed components
       `No`  Correct Answer

**5. Is there documentation?**
       `Yes`  Correct Answer
       `No`  Not eligible

**6. Does this project collect or use non-personally identifiable information (non-PII) data?**
       `Yes`  Maybe eligibile IF there is a mechanism for extracting non-PII data from the system in a non-proprietary format
       `No`  Correct Answer

**7. Does the project adhere to privacy and other applicable international and domestic laws?**
       `Yes`  Correct Answer
       `No`  Not eligible

**8. Does the project adhere to standards and best practices?**
       `Yes`  Correct Answer
       `No`  Not eligible

**9. Does the project take steps to anticipate, prevent and do no harm?** 
       `Yes`  Correct Answer
       `No`  Not eligible

@lacabra @nathanbaleeta @amreenp7 Please provide your feedback on this.

**Comment by amreenp7** [comment]
@rachita19082 - this looks good to me. Per our conversation, let's look at the following scenarios:

- If 9/9 correct completely -> Page A (You are eligible)
- If 1 wrong completely and no maybes --> Page B (You are not eligible)
- If 1 wrong completely and at least 1 maybe --> Page B (Include a "Furthermore" for the maybe question)
- If none wrong and at least 1 maybe --> Page C (You may be eligible...furthermore section)
