### ISSUE TITLE
Unresolving fonts in static WordPress pull

### ISSUE THREAD

**Issue by nathanfletcher** [unicef/publicgoods-scripts#31]
After the script pulls the WordPress sites pages, part of the subsequent steps is to build `packages/eligibility`
That throws the following error in the build process
```./src/index.css
Error: Can't resolve '/wp-content/themes/dpga/font/NowAlt-Regular.woff' in '/home/runner/work/publicgoods-scripts/publicgoods-scripts/packages/eligibility/src'```

**Comment by nathanfletcher** [comment]
This is the sandbox I'm fixing it and other minor bugs found 
https://github.com/nathanfletcher/publicgoods-scripts

**Comment by lacabra** [comment]
@nathanfletcher This may be a "non-consequential" error, that may require further investigation. For example, why is it that the error does not appear in the build that the CI does [here](https://github.com/unicef/publicgoods-candidates/blob/98770930e1a403a50239e04cffb83a7255a07eee/scripts/push.bash#L16)? (if it appeared, it would error out)

Can you please provide additional information on how this error is triggered?

**Comment by nathanfletcher** [comment]
@lacabra Creating a GitHub action in this repo to set up the CI in this repo to run `npm run build` in both folders `packages/registry` and `packages/eligibility` means that all the steps from 1-8 in the Readme would have to be followed first, with some slight modifications to include `packages/registry` and `packages/eligibility`.

Running `npm run build` for `packages/eligibility` after the steps throws this error because it cannot find `/wp-content/themes/dpga/font/NowAlt-Regular.woff` as the CSS is not able to access folders outside the `src` folder of `packages/eligibility` during the `npm run build` process.

I solved it by including a step in `moveFiles.bash` [here](https://github.com/unicef/publicgoods-scripts/blob/c036d58099ec9b0225c0dd5e8a990c0e7be8f040/scripts/moveFiles.bash#L10) to copy the fonts folder from the static wp-content into `packages/eligibility` and updated the links to the fonts in the CSS. 
That way it won't worry the upstream build command [here](https://github.com/unicef/publicgoods-candidates/blob/98770930e1a403a50239e04cffb83a7255a07eee/scripts/push.bash#L18)

**Comment by nathanfletcher** [comment]
Alternatively, a simpler solution would be for @rachita19082 to include the fonts folder with the respective fonts in the project. 
That is if the fonts used would not change anytime soon so the current solution I have above wouldn't have to pull it from the static WordPress [here](https://github.com/unicef/publicgoods-scripts/blob/06f687ac0b6932b83eb334e3ba646e4e86a0c2f0/scripts/moveFiles.bash#L10)

**Comment by lacabra** [comment]
@nathanfletcher I prefer your solution of copying them only for the purposes of the CI. Alternatively, you could do a soft link of the relative folder (because you have it cloned already -> that's how I have it in my local environment, and works well)

For sure, do not include the fonts in the source code because they don't belong there, and introduces undesired redundancy.

Thanks!
