### ISSUE TITLE
Update Eligibility Form based on User Feedback

### ISSUE THREAD

**Issue by rachita19082** [unicef/publicgoods-scripts#35]
Update the following components of the Eligibility Form based on feedback received:

**Content**

- [x] Replace "project" with "product"
- [x] Use more definitive language
- [x] Update FAQ questions and answers
- [x] Update text on the Result page for product not eligible case

**UX**

- [x] Ensure all FAQ links open in the new tab

**Comment by amreenp7** [comment]
Hi @rachita19082, just 1 comment: Everywhere on the form where we use the words "project/s" or "product/s", please replace that with "digital solution" or digital solutions"

CC: Lucy

**Comment by lacabra** [comment]
@rachita19082 please make a concerted effort to manage your issues. The moment you check all of the items in the ToDo list, this issue can be closed. Thanks!
