### ISSUE TITLE
CORS error between Eligibility form and Submission form

### ISSUE THREAD

**Issue by nathanfletcher** [unicef/publicgoods-scripts#49]
The CORS error persists when sending data to the nomination form. 

The [ next.js config file ](https://github.com/lacabra/submission-digitalpublicgoods/blob/695734397d0b5c5691231fe7d2bcb02b0ad50356/next.config.js) inside the [Submission-digital-public-goods project](https://github.com/lacabra/submission-digitalpublicgoods) does not work as intended.

A screenshot is attached below
![image](https://user-images.githubusercontent.com/1917416/129777156-ceb624d4-3082-4888-8d88-a1e7d261f80e.png)

**Comment by lacabra** [comment]
Reopening as #50 did not fix the problem
