### ISSUE TITLE
Questions/Recommendations for DPG Map 

### ISSUE THREAD

**Issue by SarahWat** [unicef/publicgoods-scripts#68]
Just updated the map content & looking great. A few suggestions/questions below: 
1. For the side navigation bar
- Can we remove "Pathfinders Exploratory" for now? I think we should only show existing pathfinders until discussions with those country offices / DPGs etc are final. 
- To fit with the above, adjust the title "Pathfinders Confirmed" to "DPG Pathfinders".
- DPGs deployed & developed - please capitalize both "Deployed" and "Developed"
- Can we add a "back" arrow that will navigate back to the cards?
2. In the bottom corner of the side navigation bar there is a link titled "Data: Pathfinders and Story" which links to the google doc. Let's remove this from the public facing version. 
3. On the home screen, is it possible to reverse the up arrows to face down towards the next card?
4. A larger question - is it possible to show a side navigation while also showing a card? (Eg. could we explain a DPG in a card and have their detailed information show on the side navigation? 

Thanks so much!

**Comment by Rolikasi** [comment]
Thank you for your suggestions @SarahWat! 🙏 

1. Agreed on everything. Right now you can scroll up to the cards, but I see that it's tricky, not user-friendly and sometimes buggy. So may be it's better to remove the ability to scroll up at all and add 'back arrow'.
2. It's a good practice to keep data sources publicly available, it makes projects open and trustful. Kindly clarify do you want to remove entire `Data: Pathfinders and Story | DPGs` or just `Pathfinders and Story`? We can remove `Pathfinders and Story` and keep the link to gdoc [here in GitHub](https://github.com/unicef/publicgoods-scripts/tree/main/packages/map#-architecture)
3. Yes, it's possible. For the better user experience let's keep arrows up for the mobile version(so it looks like swipe action) and down for desktop version.
4. I can implement this functionality next week. There will be a new column in gdoc `show navigation`.

I also see that text in cards is written more for the desktop users. For example, `menu` on mobile is placed under the map and `searchbox` is above but in cards we call it `side menu`. So we need to adapt text or store different stories for desktop/tablet/mobile users(which is paintful) or we can add disclaimer in the 1st card "For the better experience open the map in desktop browser"(which might scare readers on mobile/tablet). I think adapting text is the best option.

**Comment by Rolikasi** [comment]
Track progress:
- [x] remove "Pathfinders Exploratory"
- [x] adjust the title "Pathfinders Confirmed" to "DPG Pathfinders"
- [x] capitalize both "DPGs Deployed" and "DPGs Developed"
- [x] add back to story arrow
- [x] remove link to gdoc
- [x] reverse arrows for desktop version
- [ ] implement `showinfo` while showing cards

**Comment by Rolikasi** [comment]
@SarahWat kindly look at the screenshot bellow. I added 2 arrows near close icon. When you mouseover it the text "back to story" appends. Does it look good and intuitive?
![image](https://user-images.githubusercontent.com/44370635/133608398-ab441d3f-9cf4-4a8a-a78d-f8a17fa26ad3.png)
