### ISSUE TITLE
[Map] Summary information and SDG layer for DPG Map

### ISSUE THREAD

**Issue by edil-it-them** [unicef/publicgoods-scripts#85]
I would like to make some more improvements to the map visualization:
- There is no **summary information** about DPGs on the entire website. I can add charts to the menu that will show how many DPGs are associated with each SDG and type. The summary information will be visible when nothing is selected like in the screenshot bellow.
![image](https://user-images.githubusercontent.com/44370635/136241457-5e562949-01ca-4da3-9793-9a5942b34f64.png)

- **Add one more layer of visualization by SDGs**. It'd be great to have an ability to select one of 17 SDGs from the dropdown and see how many DPGs are related to it. I think it'll be great to show it both on the map with colors (from light to dark  depending on how many DPGs are deployed) and on side menu using barcharts with country names.

What do you think @SarahWat , @lacabra ?
cc: @nathanfletcher

**Comment by lacabra** [comment]
Both suggestions sound like great ideas to me. You have my green light to implement. Thanks! 🙏
