### ISSUE TITLE
Improve distribution by SDG data visualization 

### ISSUE THREAD

**Issue by Rolikasi** [unicef/publicgoods-scripts#9]
Right now in [registry section](https://digitalpublicgoods.net/registry/) users need to hover on rectangles in `distribution by SDG` chart to see the labels and values of data. Otherwise data visualization communicate too little information.
We can add labels of SDGs to chart. It'll improve UX and be more readable.
**Current**
![Снимок](https://user-images.githubusercontent.com/44370635/116120444-34891080-a6c8-11eb-84ed-a7fe6bded4e3.PNG)

**Suggestion**
I suggest the following design. It's clear what these rectangles are about.
![Group 10](https://user-images.githubusercontent.com/44370635/116120456-36eb6a80-a6c8-11eb-8991-2cfaec8e8d62.jpg)

**Or even better**
We can also add amount of nominees to each rectangle where it fits. We need a word `nominee` in the first rectangle to indicate what these numbers are about.
![Frame 18](https://user-images.githubusercontent.com/44370635/116120481-3d79e200-a6c8-11eb-9871-e4685b908205.jpg)

I can see that visualization is rendered in this [repo](https://github.com/unicef/publicgoods-scripts/blob/master/index.js) so I opened issue here
@lacabra what do you think?

**Comment by lacabra** [comment]
Thanks @Rolikasi. Overall I agree with you: there is room for improvement in that visualization, and I would very much appreciate your improvements as suggested above.

Two observations:
* I would add `SDG {x}` to all of them for consistency, as in your proposed design above, for example `No poverty` is missing `SDG 1`, whereas it is displayed in `SDG 7`. I agree though that I would not try to cram the text of `Affordable and Clean Energy` in SDG7

* I think I like your first design more where we keep the SDG number in a bigger font, and we add the name of the SDG, combined with the idea of displaying the number of nominees that are tagged under that category.

**Comment by Rolikasi** [comment]
You're welcome @lacabra!
I can work on this improvement. I'll try to develop this design:

![Group 10](https://user-images.githubusercontent.com/44370635/116231230-48cd1c00-a761-11eb-9219-f348f5c98a25.jpg)
I like the idea of displaying word `nominees` in the first SDG to label all values.

I want to clarify. Am I right that I need to setup site locally by following these steps in [publicgoods-wordpress](https://github.com/unicef/publicgoods-wordpress), make changes in publicgoods-scripts and push commits? Then changes in publicgoods-scripts will trigger an update in publicgoods-website.

**Comment by lacabra** [comment]
Yes, you are correct in following the setup instructions in [publicgoods-wordpress](https://github.com/unicef/publicgoods-wordpress), and push your changes to publicgoods-scripts repo. I will manually trigger an update to the actual website (or every night, the website gets updated automatically)
